"""entity and area

Revision ID: 8967e78ac7b0
Revises: 856755dc8521
Create Date: 2022-01-27 16:21:33.933387

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8967e78ac7b0"
down_revision = "856755dc8521"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "areas",
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("updated", sa.DateTime(), nullable=True),
        sa.Column("code", sa.String(length=9), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("name_welsh", sa.String(length=255), nullable=True),
        sa.Column("areachect", sa.Float(), nullable=True),
        sa.Column("areaehect", sa.Float(), nullable=True),
        sa.Column("areaihect", sa.Float(), nullable=True),
        sa.Column("arealhect", sa.Float(), nullable=True),
        sa.Column("child_count", sa.Integer(), nullable=True),
        sa.Column("child_counts", sa.JSON(), nullable=True),
        sa.Column("date_end", sa.Date(), nullable=True),
        sa.Column("date_start", sa.Date(), nullable=True),
        sa.Column("entity", sa.String(length=3), nullable=True),
        sa.Column("equivalents", sa.JSON(), nullable=True),
        sa.Column("owner", sa.String(length=255), nullable=True),
        sa.Column("parent", sa.String(length=9), nullable=True),
        sa.Column("predecessor", sa.ARRAY(sa.String(length=9)), nullable=True),
        sa.Column("successor", sa.ARRAY(sa.String(length=9)), nullable=True),
        sa.Column("sort_order", sa.String(length=9), nullable=True),
        sa.Column("statutory_instrument_id", sa.String(length=255), nullable=True),
        sa.Column("statutory_instrument_title", sa.String(length=255), nullable=True),
        sa.Column(
            "geom",
            geoalchemy2.types.Geometry(
                geometry_type="MULTIPOLYGON",
                srid=4326,
                from_text="ST_GeomFromEWKT",
                name="geometry",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_areas_name"), "areas", ["name"], unique=False)
    op.create_table(
        "entities",
        sa.Column("code", sa.String(length=9), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("abbreviation", sa.String(length=255), nullable=True),
        sa.Column("theme", sa.String(length=255), nullable=True),
        sa.Column("coverage", sa.String(length=255), nullable=True),
        sa.Column("related_codes", sa.ARRAY(sa.String(length=255)), nullable=True),
        sa.Column("status", sa.String(length=255), nullable=True),
        sa.Column("live_instances", sa.Integer(), nullable=True),
        sa.Column("archived_instances", sa.Integer(), nullable=True),
        sa.Column("crossborder_instances", sa.Integer(), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.Column("current_code_first", sa.String(length=255), nullable=True),
        sa.Column("current_code_last", sa.String(length=255), nullable=True),
        sa.Column("reserved_code", sa.String(length=255), nullable=True),
        sa.Column("owner", sa.String(length=255), nullable=True),
        sa.Column("date_introduced", sa.Date(), nullable=True),
        sa.Column("date_start", sa.Date(), nullable=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_index(op.f("ix_entities_name"), "entities", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_entities_name"), table_name="entities")
    op.drop_table("entities")
    op.drop_index(op.f("ix_areas_name"), table_name="areas")
    op.drop_table("areas")
    # ### end Alembic commands ###
