"""add hash 4

Revision ID: 95000c6b458f
Revises: 8967e78ac7b0
Create Date: 2022-01-28 21:31:13.733476

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision = '95000c6b458f'
down_revision = '8967e78ac7b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('postcodes', sa.Column('hash4', sa.String(length=4), nullable=True))
    op.create_index(op.f('ix_postcodes_hash4'), 'postcodes', ['hash4'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_postcodes_hash4'), table_name='postcodes')
    op.drop_column('postcodes', 'hash4')
    # ### end Alembic commands ###
