"""Add updated column

Revision ID: a0863ceb4005
Revises: de23b0d97017
Create Date: 2022-01-27 10:55:36.478912

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a0863ceb4005"
down_revision = "de23b0d97017"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("postcodes", sa.Column("active", sa.Boolean(), nullable=True))
    op.add_column("postcodes", sa.Column("updated", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("postcodes", "updated")
    op.drop_column("postcodes", "active")
    # ### end Alembic commands ###
