"""postcode columns

Revision ID: de23b0d97017
Revises: 5d83af1f4cb3
Create Date: 2022-01-27 10:40:35.247592

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de23b0d97017"
down_revision = "5d83af1f4cb3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "postcodes",
        "pcd2",
        existing_type=sa.VARCHAR(length=7),
        type_=sa.String(length=8),
        existing_nullable=True,
    )
    op.alter_column(
        "postcodes",
        "pcds",
        existing_type=sa.VARCHAR(length=7),
        type_=sa.String(length=8),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "postcodes",
        "pcds",
        existing_type=sa.String(length=8),
        type_=sa.VARCHAR(length=7),
        existing_nullable=True,
    )
    op.alter_column(
        "postcodes",
        "pcd2",
        existing_type=sa.String(length=8),
        type_=sa.VARCHAR(length=7),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
